package com.dickson.libraryapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class BookCopyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCopyAllPropertiesEquals(BookCopy expected, BookCopy actual) {
        assertBookCopyAutoGeneratedPropertiesEquals(expected, actual);
        assertBookCopyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCopyAllUpdatablePropertiesEquals(BookCopy expected, BookCopy actual) {
        assertBookCopyUpdatableFieldsEquals(expected, actual);
        assertBookCopyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCopyAutoGeneratedPropertiesEquals(BookCopy expected, BookCopy actual) {
        assertThat(actual)
            .as("Verify BookCopy auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCopyUpdatableFieldsEquals(BookCopy expected, BookCopy actual) {
        assertThat(actual)
            .as("Verify BookCopy relevant properties")
            .satisfies(a -> assertThat(a.getBarcode()).as("check barcode").isEqualTo(expected.getBarcode()))
            .satisfies(a -> assertThat(a.getShelfLocation()).as("check shelfLocation").isEqualTo(expected.getShelfLocation()))
            .satisfies(a -> assertThat(a.getAcquisitionDate()).as("check acquisitionDate").isEqualTo(expected.getAcquisitionDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertBookCopyUpdatableRelationshipsEquals(BookCopy expected, BookCopy actual) {
        assertThat(actual)
            .as("Verify BookCopy relationships")
            .satisfies(a -> assertThat(a.getBook()).as("check book").isEqualTo(expected.getBook()));
    }
}
