package com.dickson.libraryapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LibraryMemberAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryMemberAllPropertiesEquals(LibraryMember expected, LibraryMember actual) {
        assertLibraryMemberAutoGeneratedPropertiesEquals(expected, actual);
        assertLibraryMemberAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryMemberAllUpdatablePropertiesEquals(LibraryMember expected, LibraryMember actual) {
        assertLibraryMemberUpdatableFieldsEquals(expected, actual);
        assertLibraryMemberUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the derived primary key is set correctly.
     *
     * @param entityToPersist the entity used to persist
     * @param persisted the persisted entity
     */
    public static void assertLibraryMemberMapsIdRelationshipPersistedValue(LibraryMember entityToPersist, LibraryMember persisted) {
        // Validate the id for MapsId, the ids must be same
        assertThat(entityToPersist.getInternalUser().getId()).isEqualTo(persisted.getId());
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryMemberAutoGeneratedPropertiesEquals(LibraryMember expected, LibraryMember actual) {
        assertThat(actual)
            .as("Verify LibraryMember auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryMemberUpdatableFieldsEquals(LibraryMember expected, LibraryMember actual) {
        assertThat(actual)
            .as("Verify LibraryMember relevant properties")
            .satisfies(a -> assertThat(a.getMembershipNumber()).as("check membershipNumber").isEqualTo(expected.getMembershipNumber()))
            .satisfies(a -> assertThat(a.getPhoneNumber()).as("check phoneNumber").isEqualTo(expected.getPhoneNumber()))
            .satisfies(a -> assertThat(a.getBirthDate()).as("check birthDate").isEqualTo(expected.getBirthDate()))
            .satisfies(a -> assertThat(a.getAddress()).as("check address").isEqualTo(expected.getAddress()))
            .satisfies(a -> assertThat(a.getRegistrationDate()).as("check registrationDate").isEqualTo(expected.getRegistrationDate()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLibraryMemberUpdatableRelationshipsEquals(LibraryMember expected, LibraryMember actual) {
        // empty method
    }
}
