package com.dickson.libraryapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LoanAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoanAllPropertiesEquals(Loan expected, Loan actual) {
        assertLoanAutoGeneratedPropertiesEquals(expected, actual);
        assertLoanAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoanAllUpdatablePropertiesEquals(Loan expected, Loan actual) {
        assertLoanUpdatableFieldsEquals(expected, actual);
        assertLoanUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoanAutoGeneratedPropertiesEquals(Loan expected, Loan actual) {
        assertThat(actual)
            .as("Verify Loan auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoanUpdatableFieldsEquals(Loan expected, Loan actual) {
        assertThat(actual)
            .as("Verify Loan relevant properties")
            .satisfies(a -> assertThat(a.getLoanDate()).as("check loanDate").isEqualTo(expected.getLoanDate()))
            .satisfies(a -> assertThat(a.getDueDate()).as("check dueDate").isEqualTo(expected.getDueDate()))
            .satisfies(a -> assertThat(a.getReturnDate()).as("check returnDate").isEqualTo(expected.getReturnDate()))
            .satisfies(a -> assertThat(a.getRenewals()).as("check renewals").isEqualTo(expected.getRenewals()))
            .satisfies(a -> assertThat(a.getNotes()).as("check notes").isEqualTo(expected.getNotes()))
            .satisfies(a -> assertThat(a.getStatus()).as("check status").isEqualTo(expected.getStatus()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLoanUpdatableRelationshipsEquals(Loan expected, Loan actual) {
        assertThat(actual)
            .as("Verify Loan relationships")
            .satisfies(a -> assertThat(a.getMember()).as("check member").isEqualTo(expected.getMember()))
            .satisfies(a -> assertThat(a.getBookCopy()).as("check bookCopy").isEqualTo(expected.getBookCopy()));
    }
}
